/* eslint-disable */
// source: src/controlMessage.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

goog.exportSymbol('proto.ControlMessage', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.ControlMessage = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.ControlMessage, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.ControlMessage.displayName = 'proto.ControlMessage';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.ControlMessage.prototype.toObject = function(opt_includeInstance) {
  return proto.ControlMessage.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.ControlMessage} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.ControlMessage.toObject = function(includeInstance, msg) {
  var f, obj = {
    type: jspb.Message.getFieldWithDefault(msg, 1, 0),
    action: jspb.Message.getFieldWithDefault(msg, 2, 0),
    text: jspb.Message.getFieldWithDefault(msg, 3, ""),
    metastate: jspb.Message.getFieldWithDefault(msg, 4, 0),
    keycode: jspb.Message.getFieldWithDefault(msg, 5, 0),
    buttons: jspb.Message.getFieldWithDefault(msg, 6, 0),
    pointerid: jspb.Message.getFieldWithDefault(msg, 7, 0),
    pressure: jspb.Message.getFloatingPointFieldWithDefault(msg, 8, 0.0),
    x: jspb.Message.getFieldWithDefault(msg, 9, 0),
    y: jspb.Message.getFieldWithDefault(msg, 10, 0),
    width: jspb.Message.getFieldWithDefault(msg, 11, 0),
    height: jspb.Message.getFieldWithDefault(msg, 12, 0),
    hscroll: jspb.Message.getFieldWithDefault(msg, 13, 0),
    vscroll: jspb.Message.getFieldWithDefault(msg, 14, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.ControlMessage}
 */
proto.ControlMessage.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.ControlMessage;
  return proto.ControlMessage.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.ControlMessage} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.ControlMessage}
 */
proto.ControlMessage.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setType(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setAction(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setText(value);
      break;
    case 4:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setMetastate(value);
      break;
    case 5:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setKeycode(value);
      break;
    case 6:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setButtons(value);
      break;
    case 7:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setPointerid(value);
      break;
    case 8:
      var value = /** @type {number} */ (reader.readFloat());
      msg.setPressure(value);
      break;
    case 9:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setX(value);
      break;
    case 10:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setY(value);
      break;
    case 11:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setWidth(value);
      break;
    case 12:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setHeight(value);
      break;
    case 13:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setHscroll(value);
      break;
    case 14:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setVscroll(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.ControlMessage.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.ControlMessage.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.ControlMessage} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.ControlMessage.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getType();
  if (f !== 0) {
    writer.writeInt32(
      1,
      f
    );
  }
  f = message.getAction();
  if (f !== 0) {
    writer.writeInt32(
      2,
      f
    );
  }
  f = message.getText();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getMetastate();
  if (f !== 0) {
    writer.writeInt32(
      4,
      f
    );
  }
  f = message.getKeycode();
  if (f !== 0) {
    writer.writeInt32(
      5,
      f
    );
  }
  f = message.getButtons();
  if (f !== 0) {
    writer.writeInt32(
      6,
      f
    );
  }
  f = message.getPointerid();
  if (f !== 0) {
    writer.writeInt64(
      7,
      f
    );
  }
  f = message.getPressure();
  if (f !== 0.0) {
    writer.writeFloat(
      8,
      f
    );
  }
  f = message.getX();
  if (f !== 0) {
    writer.writeInt32(
      9,
      f
    );
  }
  f = message.getY();
  if (f !== 0) {
    writer.writeInt32(
      10,
      f
    );
  }
  f = message.getWidth();
  if (f !== 0) {
    writer.writeInt32(
      11,
      f
    );
  }
  f = message.getHeight();
  if (f !== 0) {
    writer.writeInt32(
      12,
      f
    );
  }
  f = message.getHscroll();
  if (f !== 0) {
    writer.writeInt32(
      13,
      f
    );
  }
  f = message.getVscroll();
  if (f !== 0) {
    writer.writeInt32(
      14,
      f
    );
  }
};


/**
 * optional int32 type = 1;
 * @return {number}
 */
proto.ControlMessage.prototype.getType = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {number} value
 * @return {!proto.ControlMessage} returns this
 */
proto.ControlMessage.prototype.setType = function(value) {
  return jspb.Message.setProto3IntField(this, 1, value);
};


/**
 * optional int32 action = 2;
 * @return {number}
 */
proto.ControlMessage.prototype.getAction = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/**
 * @param {number} value
 * @return {!proto.ControlMessage} returns this
 */
proto.ControlMessage.prototype.setAction = function(value) {
  return jspb.Message.setProto3IntField(this, 2, value);
};


/**
 * optional string text = 3;
 * @return {string}
 */
proto.ControlMessage.prototype.getText = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.ControlMessage} returns this
 */
proto.ControlMessage.prototype.setText = function(value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * optional int32 metaState = 4;
 * @return {number}
 */
proto.ControlMessage.prototype.getMetastate = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 4, 0));
};


/**
 * @param {number} value
 * @return {!proto.ControlMessage} returns this
 */
proto.ControlMessage.prototype.setMetastate = function(value) {
  return jspb.Message.setProto3IntField(this, 4, value);
};


/**
 * optional int32 keycode = 5;
 * @return {number}
 */
proto.ControlMessage.prototype.getKeycode = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 5, 0));
};


/**
 * @param {number} value
 * @return {!proto.ControlMessage} returns this
 */
proto.ControlMessage.prototype.setKeycode = function(value) {
  return jspb.Message.setProto3IntField(this, 5, value);
};


/**
 * optional int32 buttons = 6;
 * @return {number}
 */
proto.ControlMessage.prototype.getButtons = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 6, 0));
};


/**
 * @param {number} value
 * @return {!proto.ControlMessage} returns this
 */
proto.ControlMessage.prototype.setButtons = function(value) {
  return jspb.Message.setProto3IntField(this, 6, value);
};


/**
 * optional int64 pointerId = 7;
 * @return {number}
 */
proto.ControlMessage.prototype.getPointerid = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 7, 0));
};


/**
 * @param {number} value
 * @return {!proto.ControlMessage} returns this
 */
proto.ControlMessage.prototype.setPointerid = function(value) {
  return jspb.Message.setProto3IntField(this, 7, value);
};


/**
 * optional float pressure = 8;
 * @return {number}
 */
proto.ControlMessage.prototype.getPressure = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 8, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.ControlMessage} returns this
 */
proto.ControlMessage.prototype.setPressure = function(value) {
  return jspb.Message.setProto3FloatField(this, 8, value);
};


/**
 * optional int32 x = 9;
 * @return {number}
 */
proto.ControlMessage.prototype.getX = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 9, 0));
};


/**
 * @param {number} value
 * @return {!proto.ControlMessage} returns this
 */
proto.ControlMessage.prototype.setX = function(value) {
  return jspb.Message.setProto3IntField(this, 9, value);
};


/**
 * optional int32 y = 10;
 * @return {number}
 */
proto.ControlMessage.prototype.getY = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 10, 0));
};


/**
 * @param {number} value
 * @return {!proto.ControlMessage} returns this
 */
proto.ControlMessage.prototype.setY = function(value) {
  return jspb.Message.setProto3IntField(this, 10, value);
};


/**
 * optional int32 width = 11;
 * @return {number}
 */
proto.ControlMessage.prototype.getWidth = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 11, 0));
};


/**
 * @param {number} value
 * @return {!proto.ControlMessage} returns this
 */
proto.ControlMessage.prototype.setWidth = function(value) {
  return jspb.Message.setProto3IntField(this, 11, value);
};


/**
 * optional int32 height = 12;
 * @return {number}
 */
proto.ControlMessage.prototype.getHeight = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 12, 0));
};


/**
 * @param {number} value
 * @return {!proto.ControlMessage} returns this
 */
proto.ControlMessage.prototype.setHeight = function(value) {
  return jspb.Message.setProto3IntField(this, 12, value);
};


/**
 * optional int32 hScroll = 13;
 * @return {number}
 */
proto.ControlMessage.prototype.getHscroll = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 13, 0));
};


/**
 * @param {number} value
 * @return {!proto.ControlMessage} returns this
 */
proto.ControlMessage.prototype.setHscroll = function(value) {
  return jspb.Message.setProto3IntField(this, 13, value);
};


/**
 * optional int32 vScroll = 14;
 * @return {number}
 */
proto.ControlMessage.prototype.getVscroll = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 14, 0));
};


/**
 * @param {number} value
 * @return {!proto.ControlMessage} returns this
 */
proto.ControlMessage.prototype.setVscroll = function(value) {
  return jspb.Message.setProto3IntField(this, 14, value);
};


goog.object.extend(exports, proto);
